### ISSUE TITLE
Panic in compressor

### ISSUE THREAD

**Issue by achille-roussel** [pierrec/lz4#116]
Hello,

I'm opening this issue to report a panic which seems to originate in the lz4 code:
```
panic: runtime error: index out of range [65536] with length 65536

goroutine 611853 [running]:
github.com/pierrec/lz4/v4/internal/lz4block.(*Compressor).CompressBlock(0xc055bc0000, 0xc054c40000, 0x10000, 0x10000, 0xc05597e000, 0x10000, 0x10000, 0x70, 0x1071c60, 0xf32701)
        /go/src/github.com/segmentio/tracing/cmd/tracedb/vendor/github.com/pierrec/lz4/v4/internal/lz4block/block.go:191 +0xbbe
github.com/pierrec/lz4/v4/internal/lz4block.CompressBlock(0xc054c40000, 0x10000, 0x10000, 0xc05597e000, 0x10000, 0x10000, 0x7, 0xc03b56b588, 0xe2ca51)
        /go/src/github.com/segmentio/tracing/cmd/tracedb/vendor/github.com/pierrec/lz4/v4/internal/lz4block/block.go:91 +0xa7
github.com/pierrec/lz4/v4/internal/lz4stream.(*FrameDataBlock).Compress(0xc04d904150, 0xc0488fe240, 0xc054c40000, 0x10000, 0x10000, 0xc000000000, 0xe300f1)
        /go/src/github.com/segmentio/tracing/cmd/tracedb/vendor/github.com/pierrec/lz4/v4/internal/lz4stream/block.go:221 +0xa5
github.com/pierrec/lz4/v4.(*Writer).write(0xc0488fe2d0, 0xc054c40000, 0x10000, 0x10000, 0x200000000, 0xc03b56b638, 0xe2af4e)
        /go/src/github.com/segmentio/tracing/cmd/tracedb/vendor/github.com/pierrec/lz4/v4/writer.go:128 +0x7a
github.com/pierrec/lz4/v4.(*Writer).Write(0xc0488fe2d0, 0xc054c40000, 0x10000, 0x10000, 0x0, 0x0, 0x0)
        /go/src/github.com/segmentio/tracing/cmd/tracedb/vendor/github.com/pierrec/lz4/v4/writer.go:94 +0x508
```

For reference, this is how we constructed the writer:
```go
	x := lz4.NewWriter(w)
	x.Apply(
		lz4.BlockSizeOption(lz4.Block64Kb),
		lz4.ConcurrencyOption(1),
	)
```

In case this helps identify the issue, the software that hit this condition is writing buffers of exactly 64KB, and reusing the writers with calls to `Reset`.

**Comment by pierrec** [comment]
Thanks for the report, will look into it.

**Comment by achille-roussel** [comment]
This happened as well with the block size option set to 256KB, compressing data blocks of exactly 256 KB:

```
panic: runtime error: index out of range [262144] with length 262144

goroutine 25648 [running]:
github.com/pierrec/lz4/v4/internal/lz4block.(*Compressor).CompressBlock(0xc0b037e000, 0xc05473e000, 0x40000, 0x40000, 0xc0b03d0000, 0x40000, 0x40000, 0x101, 0xc064984da0, 0xc064984e18)
	/go/src/github.com/segmentio/tracing/cmd/tracedb/vendor/github.com/pierrec/lz4/v4/internal/lz4block/block.go:191 +0xbbe
github.com/pierrec/lz4/v4/internal/lz4block.CompressBlock(0xc05473e000, 0x40000, 0x40000, 0xc0b03d0000, 0x40000, 0x40000, 0x7, 0xc064984eb8, 0xe32071)
	/go/src/github.com/segmentio/tracing/cmd/tracedb/vendor/github.com/pierrec/lz4/v4/internal/lz4block/block.go:91 +0xa7
github.com/pierrec/lz4/v4/internal/lz4stream.(*FrameDataBlock).Compress(0xc051b07c00, 0xc051bea510, 0xc05473e000, 0x40000, 0x40000, 0xc000000000, 0xe35711)
	/go/src/github.com/segmentio/tracing/cmd/tracedb/vendor/github.com/pierrec/lz4/v4/internal/lz4stream/block.go:221 +0xa5
github.com/pierrec/lz4/v4.(*Writer).write(0xc051bea5a0, 0xc05473e000, 0x40000, 0x40000, 0x200000000, 0xc064984f68, 0xe3056e)
	/go/src/github.com/segmentio/tracing/cmd/tracedb/vendor/github.com/pierrec/lz4/v4/writer.go:128 +0x7a
github.com/pierrec/lz4/v4.(*Writer).Write(0xc051bea5a0, 0xc05473e000, 0x40000, 0x40000, 0x0, 0x0, 0x0)
```

**Comment by pierrec** [comment]
Glancing at the code, nothing jumps at me.
Any chance to get a reproducer?
