### ISSUE TITLE
TestCopy hangs on armhf

### ISSUE THREAD

**Issue by danstender** [pierrec/lz4#9]
Hi,
we have build problems with lz4 on armhf (v7 set like Cortex-a8), TestCopy hangs:
```
=== RUN   TestCopy
SIGQUIT: quit
PC=0x6fcfc m=0

goroutine 28155 [running]:
bytes.Equal(0x13060000, 0x400000, 0x700000, 0x10576000, 0x400000, 0xa00000)
	/usr/lib/go-1.7/src/runtime/asm_arm.s:893 +0x28 fp=0x10541dd4 sp=0x10541dd4
github.com/pierrec/lz4_test.TestCopy(0x10572100)
	/home/stender/sandbox/golang-github-pierrec-lz4-0.0~git20151216.222ab1f/obj-arm-linux-gnueabihf/src/github.com/pierrec/lz4/lz4_test.go:510 +0x830 fp=0x10541fa8 sp=0x10541dd4
testing.tRunner(0x10572100, 0x15c6f4)
	/usr/lib/go-1.7/src/testing/testing.go:610 +0xa4 fp=0x10541fcc sp=0x10541fa8
runtime.goexit()
	/usr/lib/go-1.7/src/runtime/asm_arm.s:998 +0x4 fp=0x10541fcc sp=0x10541fcc
created by testing.(*T).Run
	/usr/lib/go-1.7/src/testing/testing.go:646 +0x304

goroutine 1 [chan receive, 2 minutes]:
testing.(*T).Run(0x10572100, 0x14906a, 0x8, 0x15c6f4, 0xa1901)
	/usr/lib/go-1.7/src/testing/testing.go:647 +0x324
testing.RunTests.func1(0x10516100)
	/usr/lib/go-1.7/src/testing/testing.go:793 +0xb8
testing.tRunner(0x10516100, 0x1053eed4)
	/usr/lib/go-1.7/src/testing/testing.go:610 +0xa4
testing.RunTests(0x15c714, 0x1c3120, 0x8, 0x8, 0xa00001)
	/usr/lib/go-1.7/src/testing/testing.go:799 +0x388
testing.(*M).Run(0x1053ef7c, 0x100000)
	/usr/lib/go-1.7/src/testing/testing.go:743 +0x8c
main.main()
	github.com/pierrec/lz4/_test/_testmain.go:76 +0x118

trap    0x6
error   0x0
oldmask 0x0
r0      0x1332bbce
r1      0x13460000
r2      0x10841bcd
r3      0x400000
r4      0x6f
r5      0x4c
r6      0x400000
r7      0x15c858
r8      0x11a863c0
r9      0x0
r10     0x10500960
fp      0x1c4114
ip      0x1b2728
sp      0x10541dd4
lr      0x95284
pc      0x6fcfc
cpsr    0x20000010
fault   0x0
*** Test killed with quit: ran too long (10m0s).
FAIL	github.com/pierrec/lz4	600.079s
```
The package is tried to build against Golang 1.7.
Best,
DS

**Comment by pierrec** [comment]
Hello,

It could be that the tests takes too long to run on that platform.
Try increasing the timeout to half an hour or more using the -timeout flag:
go test -timeout 30m

Let me know how this goes.

**Comment by danstender** [comment]
This works. Great! Thx.

**Comment by danstender** [comment]
BTW on [this machine](https://db.debian.org/machines.cgi?host=harris) this test takes a little over 10 minutes.
